# We don't need to use `sudo`, and can instead use containers for faster builds
sudo: false
# This is a JS project
language: node_js
# Use latest stable node version
node_js:
  - lts/*
branches:
  only:
    # Only run branch builds on master to prevent double builds on pull requests
    - master
    # Allow branches representing tags, otherwise the deploy step won't trigger
    - "/^\\d+\\.\\d*\\.?\\d*$/"
# Use `npm ci` instead of default `npm install` for installing dependencies
install:
  - npm ci
cache:
  directories:
    - "$HOME/.npm"
    - ~/.cache
script:
  - npm run test
  - npm run compile
  # Archive the built files in preparation of uploading them to Github
before_deploy:
  - tar -zcvf venus-html5-app.tar.gz dist/
deploy:
  # Upload artifacts to Github Releases - use `releases` provider
  provider: releases
  api_key:
    secure: "mO321IPszJWWHR6LBDoZSkxUWJcF7sJqGzG4GxLGtquK5yumFN4m7OjM7JxvYjBpQu1EqE3gBLB1Uk+Zw1mWXL8emt9sWJ5et6CY5r3Rd/esp1WgrwO2L32V2E+4Sehye+YOqwPifzD6XUuCmVpSr+JBfuO2zQcOlj2lIteSfImTJbVyQ5EE12zgf859C6UiVF7PR2WPkOgHINoeMW5w+dGqSQEKGvIXA9DzGitTg2N2DQP79EkHbS2pvASP0zEXGNrXlgPweYVc1iNge2blI/iq0u0mBKCLetqlVM3OwwO/Q4rnTdpAyFU3Bxa+sbbLUx8Prc9eOgeom6DfSvrSRlUE/yFQqSqs9MkSbRZggOcjOGANNtT4v4jF6tZrYUodhcEzREE1Ca+Qndp3rdCJtOtpfC9/2FXo1gt2df3hVXaiBUcKofYd4b31QnHaIJEyEUUipTnkUAzzIqJbBrLm+O7FS8i5O5WL8+PpeNaI3w2UlzfMfJUo3KhSd2ev8ewMYbwUuNGjLJ124Z7L0KszVjYtOB9sxsJi3PeKyzF8LxlUGlCB5aL1IK4lGMa9rmI8e5+dBq3DupMPdjxWerxcMqwe3jGSagPe23DP0b36GivDTiTEHbdtE6HCJ1wG2TE+1vRLjC/UZ0RzHT33lVVcao479sJacxEE/WskeoJkCGw="
  skip_cleanup: true
  # Upload archive build `before_deploy`
  file: venus-html5-app.tar.gz
  # Trigger release on tags
  on:
    repo: victronenergy/venus-html5-app
    tags: true
