language: node_js

# Use Docker for running venus-docker simulations during testing
services:
  - docker

# Use latest stable node version
node_js:
  - lts/*

addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default
      - libgconf-2-4

## Cache NPM folder and Cypress binary
cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm ci

script:
  - npm run compile
  - npm run serve:ci &
  - docker run -d --rm -p 9001:9001 -p 1883:1883 -p 3000:3000 -p 8080:80 --name venus-docker aleximb/venus-docker:latest /root/run_with_simulation.sh z
  - npm run test:ci


# Archive the built files in preparation of uploading them to Github
before_deploy:
  - tar -zcvf venus-html5-app.tar.gz dist/
deploy:
  # Upload artifacts to Github Releases - use `releases` provider
  provider: releases
  api_key:
    secure: "h0bQoqutPVyonmNLOG9dYpomXo2yN0ArdxYFD8iHbdttTg2MQOEsPUrLWzTXTZk/4Jo/c0Y58Bz0ZDCUNnlHT/SUqaoT2fUAQ4OhEFj4TYwtPxSYdt+S9edCu19eFnA9oN28AT1kXqK01aZh/aTz8fE3ll7/h75AwJVNvCFo/Iprt+YGgpMUMFmr2q2WH488c78D3pMdyMuvYJLG3dEaVxGkPe5c1HaGeRi5/rHOqepHmT79bddhe+z1AkaN4XOJFq2MJFSDJBseXNOndV+MG8ZFG1LbXadEDJFwSNvywN3Q8ixpCR44YZvH1p3MbJnFR+rXa23CPqky2kD/NFc6ETm5VhGxr2u6V6+2/qd18X/WigTFT1UQxwi+zwUnxaQq/1lT1+uXlRyhan0Q+D55krZ3EBkK54T+ZzNsVEHFccW13dtJrqPdYRujC7i4lItK40odMx0EBu8L/kqcGFYPcyPGB2O7RlQnqGA+njhQAp1eHE2pIum58faxf34fjYr7/BUV2SEIDva2E/tz/dXj7KSfte123izhl/qLXnNdR01p6yrDvOgf0Ag4JH5vrjkcEkIAHGxTdPIq9juuk10EqI+CATdk0rqixy5m/lgladNnvNk7it41zrzsLwnTVr2l6YlxRDEr7S8tLMkuRDDEMU5PEHfFDXXVCa9MTMd/Eh4="
  skip_cleanup: true
  # Upload archive build `before_deploy`
  file: venus-html5-app.tar.gz
  # Trigger release on tags
  on:
    tags: true
    all_branches: true
    condition: $TRAVIS_TAG =~ ^\d+\.\d*.?\d*$
