# We don't need to use `sudo`, and can instead use containers for faster builds
sudo: false
# This is a JS project
language: node_js
# Use latest stable node version
node_js:
  - lts/*
branches:
  only:
    # Only run branch builds on master to prevent double builds on pull requests
    - master
    # Allow branches representing tags, otherwise the deploy step won't trigger
    - "/^\\d+\\.\\d*\\.?\\d*$/"
# Use `npm ci` instead of default `npm install` for installing dependencies
install:
  - npm ci
cache:
  directories:
    - "$HOME/.npm"
    - ~/.cache
script:
  - npm run test
  - npm run compile
  # Archive the built files in preparation of uploading them to Github
before_deploy:
  - tar -zcvf venus-html5-app.tar.gz dist/
deploy:
  # Upload artifacts to Github Releases - use `releases` provider
  provider: releases
  api_key:
    secure: Z7+WibLSPv4L66ni9UlfI+mH2W1lUE92C1rPtdZYErImhwxyPmBS1+ZnGh7oZNZZPa3TvrXZNUCS6QUBN+E6NOhFDiIUmT7woLNgYvDr6kjwPFOz2/H/AM1fCQx6NmnYqMwVDEF1HRtEokNqQLPW9vzXmdgEg7DLH/3BOqWv+Xgn0vN3ocH8ugS6jBLwOVvz15riqHnaDAZ+ZT4+kivxkYFbc5z/VWnvcuq0iYqenZcKo/ImSColfWN6KXxXG/fIfWmiwxIR+8kHWdO2nZ9nFDc6WgJggENx2ot77WkVxEqzZZONkaqh9eJjoIxUgBTMJhbksiXlW+cFQEf+ePcHuv55v4bKr49ZKUQkkEzyYQkTXjd0IHw3oGqrcRrsGuPPQEXKk9HDNxsjuCWo3aioQmwEA3dzRKaSM8q1zW4IDeEJ2xQCKlucAyG9P7mhwMssa46BRizbSqIxeR6SKFf2Buco2EYuxmSn7ve3VzhJEoXxI5LJ/ACgDOqcqhHL2i0LYl9owtSA3hHqXZEthXNZBg39l5wvnWgRayTdZkujRgZr4gQG25jeMAb61RI9rkaYCvwzlzos103/XIHrtq6wvodU6FSIGCjnWdVhy0XmrdwZCP6QZ7gwZvZFP6UgRQIUi7xYmky3WTkaBIGpG7tQP++fsKesOyqhC0k9D7mtWJQ=
  skip_cleanup: true
  # Upload archive build `before_deploy`
  file: venus-html5-app.tar.gz
  # Trigger release on tags
  on:
    repo: victronenergy/venus-html5-app
    tags: true
